name: aulaaplicacaonuvem-pipeline
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Steps examples"
